=== LuisGSanchez21/WsLMGSI/05XSD/Actividad15/Actividad15.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="ciudad">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nombre">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:pattern value="[A-Z][a-z]{2,19}"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="población">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:minInclusive value="100"></xs:minInclusive>
                            <xs:maxInclusive value="100000"></xs:maxInclusive>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="alcalde">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]{0,9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>   
                            <xs:element name="apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z][a-z]*\s[A-Z}\[a-z]*"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="teléfono">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="\+34\d{9}"/>
                                  </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="tarjeta_crédito"></xs:element>
                            <xs:element name="correo_electrónico">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[^@]+@[^\.]+\..+"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="edad" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:integer">
                                    <xs:minInclusive value="18"></xs:minInclusive>
                                    <xs:maxInclusive value="120"></xs:maxInclusive>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
                <xs:element name="funcionarios" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre_y_apellidos">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="50"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="código_postal">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:pattern value="\d{5}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha_de_nacimiento">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{2}/\d{2}/\d{4}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="contrasenia">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z](\d{2}[0-9%$@!]){1,}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="número_cuenta_bancaria">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="ES\d{4}\s\d{4}\s\d{4}"></xs:pattern>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value=".{10}"></xs:pattern>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="código_identificador">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="\D{2}-\d{2,5}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LuisGSanchez21/WsLMGSI/05XSD/Actividad15/Actividad15.xml
<?xml version="1.0" encoding="UTF-8"?>  
<ciudad xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:noNamespaceSchemaLocation="Actividad15.xsd"
    código_identificador="AB-4715">
    <nombre>Madrid</nombre>
    <población>1000</población>
    <alcalde edad="108">
        <nombre>Dandy</nombre>
        <apellidos>De Barcelona</apellidos> 
        <teléfono>+34711582698</teléfono>
        <tarjeta_crédito>7984645132165647</tarjeta_crédito>
        <correo_electrónico>jose21@gmail.com</correo_electrónico>
    </alcalde>
    <funcionarios id="7894561230">
        <nombre_y_apellidos>Homero Simson</nombre_y_apellidos>
        <código_postal>28507</código_postal>
        <fecha_de_nacimiento>09/12/1987</fecha_de_nacimiento>
        <contrasenia>X65709264@</contrasenia>
        <número_cuenta_bancaria>ES7894 5649 1234</número_cuenta_bancaria>
    </funcionarios>
    <funcionarios id="8974561324">
        <nombre_y_apellidos>Peter Griffin</nombre_y_apellidos>
        <código_postal>24789</código_postal>
        <fecha_de_nacimiento>05/06/1997</fecha_de_nacimiento>
        <contrasenia>S87978897989789%</contrasenia>
        <número_cuenta_bancaria>ES7897 7895 7455</número_cuenta_bancaria>
    </funcionarios>
</ciudad>
